name: Build with Nuitka

on:
  push:
    tags:
      - 'v*'  # 自动触发：打 tag 时构建
  workflow_dispatch:  # 手动触发选项
    inputs:
      platform:
        description: 'Target platform (all/windows/linux/macos)'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - windows
          - linux
          - macos

jobs:
  build:
    strategy:
      matrix:
        include:
          # 根据手动输入或默认值动态包含平台
          - ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.platform == 'windows' || github.event_name != 'workflow_dispatch' && 'windows' }}
            os: windows-latest
            suffix: windows
          - ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.platform == 'linux' || github.event_name != 'workflow_dispatch' && 'linux' }}
            os: ubuntu-latest
            suffix: linux
          - ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.platform == 'macos' || github.event_name != 'workflow_dispatch' && 'macos' }}
            os: macos-latest
            suffix: macos
        # 自动过滤掉未启用的平台
        exclude:
          - ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.platform != 'all' && github.event.inputs.platform != 'windows' }}
            os: windows-latest
          - ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.platform != 'all' && github.event.inputs.platform != 'linux' }}
            os: ubuntu-latest
          - ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.platform != 'all' && github.event.inputs.platform != 'macos' }}
            os: macos-latest
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        pip install nuitka
        [ -f requirements.txt ] && pip install -r requirements.txt || echo "No requirements.txt"
    
    - name: Build Executable
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          python -m nuitka --standalone --onefile \
            --windows-icon-from-ico=3.ico \
            --windows-console-mode=disable \
            --output-dir=dist \
            --remove-output \
            3.py
          7z a -tzip release-${{ matrix.suffix }}.zip dist/*
        else
          python -m nuitka --standalone --onefile \
            --output-dir=dist \
            --remove-output \
            3.py
          tar -czvf release-${{ matrix.suffix }}.tar.gz dist/*
        fi
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.suffix }}-build
        path: |
          release-${{ matrix.suffix }}.*
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release-*
