name: Build with Nuitka

on:
  push:
    tags:
      - 'v*'  # 自动触发：打 tag 时构建
  workflow_dispatch:  # 手动触发选项
    inputs:
      platform:
        description: 'Target platform (留空则构建所有平台)'
        required: false
        default: 'all'
        type: choice
        options:
        - all
        - windows
        - linux
        - macos

jobs:
  build:
    strategy:
      matrix:
        os: ${{ contains(github.event.inputs.platform, 'all') && '[windows-latest, ubuntu-latest, macos-latest]' || 
             (github.event.inputs.platform == 'windows' && '[windows-latest]' ||
              github.event.inputs.platform == 'linux' && '[ubuntu-latest]' ||
              github.event.inputs.platform == 'macos' && '[macos-latest]' ||
              '[windows-latest, ubuntu-latest, macos-latest]') }}
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        pip install nuitka
        # 如果有其他依赖
        pip install -r requirements.txt
    
    - name: Build Windows Executable
      if: runner.os == 'Windows'
      run: |
        python -m nuitka --standalone --onefile --windows-icon-from-ico=3.ico --windows-console-mode=disable --output-dir=dist --remove-output 3.py
        7z a -tzip release-windows.zip dist/*
    
    - name: Build Linux Executable
      if: runner.os == 'Linux'
      run: |
        python -m nuitka --standalone --onefile --output-dir=dist --remove-output 3.py
        tar -czvf release-linux.tar.gz dist/*
    
    - name: Build MacOS Executable
      if: runner.os == 'macOS'
      run: |
        python -m nuitka --standalone --onefile --output-dir=dist --remove-output 3.py
        tar -czvf release-macos.tar.gz dist/*
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }}-build
        path: |
          release-*.zip
          release-*.tar.gz
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release-*.zip
          release-*.tar.gz
