name: Release

on:
  push:
    tags:
      - 'v*'  # 仅在推送以 "v" 开头的标签时触发

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # 设置 Python 版本

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
          choco install windows-sdk-10.0

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade nuitka
          pip install --upgrade ttkbootstrap
          pip install ordered-set  # Required by Nuitka
          pip install zstandard

      - name: Download Dependency Walker
        run: |
          $ProgressPreference = 'SilentlyContinue'
          New-Item -Path "$env:LOCALAPPDATA\Nuitka\Nuitka\Cache\downloads\depends" -ItemType Directory -Force
          Invoke-WebRequest -Uri "https://dependencywalker.com/depends22_x64.zip" -OutFile "$env:LOCALAPPDATA\Nuitka\Nuitka\Cache\downloads\depends\depends.zip"
          Expand-Archive -Path "$env:LOCALAPPDATA\Nuitka\Nuitka\Cache\downloads\depends\depends.zip" -DestinationPath "$env:LOCALAPPDATA\Nuitka\Nuitka\Cache\downloads\depends\x86_64" -Force

      - name: Build executable
        run: |
          python -m nuitka --assume-yes-for-downloads --standalone --windows-console-mode=disable --output-dir=dist --remove-output --enable-plugin=tk-inter --windows-icon-from-ico=3.ico --msvc=14.3 --windows-uac-admin --windows-company-name="FF14 CCMT" --windows-product-name="FF14角色配置管理工具" --windows-file-version=1.0.0 --windows-product-version=1.0.0 --windows-file-description="FF14角色配置管理工具" --disable-console --output-filename="FF14角色配置管理工具.exe" 3.py

      - name: Debug Build Output
        run: |
          Write-Host "Current directory:"
          pwd
          Write-Host "`nDist directory contents:"
          Get-ChildItem -Path "dist" -Recurse
          Write-Host "`nLooking for executable:"
          Get-ChildItem -Path "dist" -Recurse -Filter "*.exe"

      - name: Prepare Release Files
        run: |
          # 创建发布目录
          mkdir release
          # 查找可执行文件
          $exePath = Get-ChildItem -Path "dist" -Recurse -Filter "*.exe" | Select-Object -First 1
          if ($exePath) {
            Write-Host "Found executable at: $($exePath.FullName)"
            # 复制主程序
            Copy-Item $exePath.FullName -Destination "release/FF14角色配置管理工具.exe"
            # 复制依赖文件夹
            $distFolder = $exePath.Directory
            Copy-Item "$($distFolder.FullName)/*" -Destination "release/" -Recurse -Exclude "*.exe"
            # 创建 ZIP 文件
            Compress-Archive -Path "release/*" -DestinationPath "FF14角色配置管理工具.zip" -Force
          } else {
            Write-Host "No executable found in dist directory!"
            exit 1
          }

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: FF14角色配置管理工具.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for release keyword
        if: contains(github.event.head_commit.message, 'release')
        run: echo "Release keyword found in commit message. Proceeding with release."
